// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://denzwfstlvuziljjshqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlbnp3ZnN0bHZ1emlsampzaHFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0ODAwMjQsImV4cCI6MjA2MzA1NjAyNH0.5YRUx2J_PmOl1TfveE4_VLGyNm36_gjVhnqj0isofzE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);